In [1]:
import pandas as pd

In [2]:
rank10 = pd.read_csv("./rank_top_10_molecules.csv", index_col=0)
rank10.drop(columns=["Unnamed: 0"], inplace=True)
rank10.head()

,smiles,BBBP_Score,transformed_SAScore,nr-ar,nr-ar-lbd,nr-ahr,nr-aromatase,nr-er,nr-er-lbd,nr-ppar-gamma,sr-are,sr-atad5,sr-hse,sr-mmp,sr-p53,total,rank
0,COc1ccccc1N1CCN(C(=O)Nc2ccccc2C)CC1,0.974694,0.020517,0.079317,0.082571,0.078800,0.069113,0.070744,0.083292,0.082453,0.068816,0.083288,0.083308,0.081498,0.082355,1.899733,1
1,COc1ccccc1N1CCN(C(=O)Nc2ccccc2F)CC1,0.975394,0.027805,0.080156,0.083060,0.079669,0.071584,0.073692,0.083218,0.082949,0.068236,0.082876,0.083311,0.081828,0.080389,1.898558,2
2,COc1ccccc1NC(=O)N1CCN(Cc2ccccc2)CC1,0.970438,0.005800,0.082354,0.083083,0.076208,0.079669,0.070531,0.083132,0.082729,0.056084,0.083267,0.076745,0.077663,0.081210,1.897311,3
3,COc1ccc(NC(=O)N2CCOCC2)cc1F,0.951761,0.035180,0.080106,0.083305,0.080994,0.081588,0.081984,0.082394,0.080516,0.078597,0.082991,0.081979,0.081108,0.082374,1.894517,4
4,COc1ccccc1NC(=O)N1CCN(c2ccccc2)CC1,0.969156,0.005323,0.082736,0.082926,0.074853,0.075315,0.069438,0.083288,0.082911,0.059347,0.083264,0.081749,0.074913,0.079149,1.893722,5

In [3]:
groups = pd.read_csv("./merge_data_with_lipinski_tanimoto_and_common(only_smiles).csv", index_col=0)
groups.head()

                                              smiles
0  Cc1ccc([C@@H]2C(C(=O)c3cc(C)ccc3C)=C(O)C(=O)N2...
1  C[C@@H]1CC=C[C@@H]2[C@@H]3O[C@]3(C)[C@H](C)[C@...
2  COc1ccccc1/C=C1\SC(Nc2ccccc2)=C(C(=O)NC2CCN(C)...
3        C#CCOc1c(I)cc([C@H]2NC(=O)c3ccccc3O2)cc1OCC
4  C=C(C)CN1C(=O)N[C@@](CC)(C2CCN(C(=O)c3cc(C)nc4...

In [4]:
len(groups)

70244

In [5]:
only_common = pd.read_csv("./final_common_data_between_lipinski_and_tanimoto.csv", index_col=0)
only_common.head()

,smiles,zinc_id,MolWt,LogP,HDonors,HAcceptors,cluster,docking_score_lipinski,tanimoto_similarity,docking_score_tanimoto
0,COc1ccc(C2(C(=O)N3CCN(c4ccc(C(F)(F)F)cn4)CC3)C...,72402142,449.473,3.5060,0,5,6,-7.2,0.803030,-7.8
1,CC(=O)c1ccc(OCCCC(=O)Nc2cc(C(F)(F)F)ccc2N2CCOC...,9632279,450.457,4.5423,1,5,6,-8.1,0.850746,-7.9
2,C/C=C/c1ccc(OCC(=O)Nc2cc(C(F)(F)F)ccc2N2CCOCC2...,15940645,450.457,4.6012,1,5,6,-8.7,0.826087,-7.9
3,O=C(CN(Cc1ccco1)C1CCCC1)Nc1cc(C(F)(F)F)ccc1N1C...,58010304,451.489,4.5183,1,5,6,-8.0,0.815385,-5.9
4,COc1ccccc1NC(=O)N1CCC(CNC(=O)Nc2cccc(C(F)(F)F)...,44005198,450.461,4.7796,3,3,6,-8.3,0.805970,-7.5

In [6]:
lst_1 = []

for i in range(len(rank10)):
    for x in range(len(only_common)):
        if rank10["smiles"].iloc[i] == only_common["smiles"].iloc[x]:
            lst_1.append(x)

In [7]:
lst_1

[]

In [8]:
lst_2 = []

for i in range(len(rank10)):
    for y in range(len(groups)):
        if rank10["smiles"].iloc[i] == groups["smiles"].iloc[y]:
            lst_2.append(y)

In [9]:
lst_2

[65927, 65956, 65966, 68232, 66428, 65259, 66006, 65960, 65941, 69807]

In [10]:
# 0 <= x <= 65125 (index 기준) : K-means clustering group
# 65126 <= x <= 70245 : Tanimoto similarity group

In [12]:
k_means_lst = []
tanimoto_lst = []

for i in lst_2:
    if 0 <= i <= 65125:
        k_means_lst.append(i)
    else:
        tanimoto_lst.append(i)

print(len(k_means_lst))
print(len(tanimoto_lst))

0
10

### Comparing top 10 with ZN27

In [2]:
import pandas as pd

In [3]:
top10 = pd.read_csv("./rank_top_10_molecules.csv", index_col=0)
top10.head()

,Unnamed: 0,smiles,BBBP_Score,transformed_SAScore,nr-ar,nr-ar-lbd,nr-ahr,nr-aromatase,nr-er,nr-er-lbd,nr-ppar-gamma,sr-are,sr-atad5,sr-hse,sr-mmp,sr-p53,total,rank
0,22562,COc1ccccc1N1CCN(C(=O)Nc2ccccc2C)CC1,0.974694,0.020517,0.079317,0.082571,0.078800,0.069113,0.070744,0.083292,0.082453,0.068816,0.083288,0.083308,0.081498,0.082355,1.899733,1
1,22576,COc1ccccc1N1CCN(C(=O)Nc2ccccc2F)CC1,0.975394,0.027805,0.080156,0.083060,0.079669,0.071584,0.073692,0.083218,0.082949,0.068236,0.082876,0.083311,0.081828,0.080389,1.898558,2
2,22583,COc1ccccc1NC(=O)N1CCN(Cc2ccccc2)CC1,0.970438,0.005800,0.082354,0.083083,0.076208,0.079669,0.070531,0.083132,0.082729,0.056084,0.083267,0.076745,0.077663,0.081210,1.897311,3
3,23946,COc1ccc(NC(=O)N2CCOCC2)cc1F,0.951761,0.035180,0.080106,0.083305,0.080994,0.081588,0.081984,0.082394,0.080516,0.078597,0.082991,0.081979,0.081108,0.082374,1.894517,4
4,22868,COc1ccccc1NC(=O)N1CCN(c2ccccc2)CC1,0.969156,0.005323,0.082736,0.082926,0.074853,0.075315,0.069438,0.083288,0.082911,0.059347,0.083264,0.081749,0.074913,0.079149,1.893722,5